<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Aspire.Hosting.Garage</AssemblyName>
    <RootNamespace>Aspire.Hosting.Garage</RootNamespace>
    <PackageId>Aspire.Hosting.Garage</PackageId>
    <Version>0.1.0-preview.4</Version>
    <IsPackable>true</IsPackable>
    <Description>Garage S3 object storage integration for Aspire.</Description>
    <Authors>Patrick Matthiesen</Authors>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageTags>aspire;hosting;integration;garage;s3</PackageTags>
    <RepositoryUrl>https://github.com/PatrickMatthiesen/Aspire.Hosting.Garage</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" />
    <None Include="../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
